const herramientas = [ {
    "id" : 1,
    "producto" : "cutter profecinal",
    "img": "./imagenes/cutter.jpg" ,
    "precio" : 798,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},   
{
    "id" : 2,
    "producto" : "pinza pico de loro",
    "img": "./imagenes/pinza-pico-de-loro.jpg",
    "precio" : 1768,
    "peso" : "0.180 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},  
{
    "id" : 3,
    "producto" : "llaves combinadas",
    "img": "./imagenes/llaves-combinadas.jpg",
    "precio" : 4298,
    "peso" : "0.220 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 4,
    "producto" : "pinza perro",
    "img": "./imagenes/pinzaPerro.jpg",
    "precio" : 3498,
    "peso" : "0.150 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 5,
    "producto" : "juego de crique",
    "img": "./imagenes/juego-crique.jpg",
    "precio" : 12398,
    "peso" : "12.930 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},

{
    "id" : 6,
    "producto" : "engrampadora neumatica",
    "img": "./imagenes/engrampadora-neumatica.jpg",
    "precio" : 40798,
    "peso" : "3.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 7,
    "producto" : "torquimetro",
    "img": "./imagenes/torquimetro.jpg",
    "precio" : 4798,
    "peso" : "5.500 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 8,
    "producto" : "alicate",
    "img": "./imagenes/alicate.jpg",
    "precio" : 2498,
    "peso" : "0.890 kg",
    "categoria" : "herramintas de mano.jpg",
    "oferta" : false,
},
{
    "id" : 9,
    "producto" : "arco de sierra",
    "img": "./imagenes/arcoDeSierra.jpg",
    "precio" : 3050,
    "peso" : "0.110 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 10,
    "producto" : "engrampadora profecional",
    "img": "./imagenes/engrampadora.jpg",
    "precio" : 2380,
    "peso" : "0.450 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 11,
    "producto" : "caja ingletadora ",
    "img": "./imagenes/ingletadora.jpg",
    "precio" : 7798,
    "peso" : "0.320 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 12,
    "producto" : "puntas torx",
    "img": "./imagenes/puntas-torx.jpg",
    "precio" : 1730,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 13,
    "producto" : "escuadra acero ",
    "img": "./imagenes/escuadra.jpg",
    "precio" : 2495,
    "peso" : "0.130 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 14,
    "producto" : "destornillador 6 puntas",
    "img": "./imagenes/destornillador-porta-puntas.jpg",
    "precio" : 6798,
    "peso" : "1.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 15,
    "producto" : "pesca tornillos flexible ",
    "img": "./imagenes/pesca-tornillos-flexible.jpg",
    "precio" : 3260,
    "peso" : "0.090 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 16,
    "producto" : "calibre",
    "img": "./imagenes/calibreAcero.jpg",
    "precio" : 2798,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 17,
    "producto" : "escuadra magnetica",
    "img": "./imagenes/soporte-magnetico.jpg",
    "precio" :2858,
    "peso" : "0.080 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 18,
    "producto" : "remachadora",
    "img": "./imagenes/remachadora.jpg",
    "precio" : 54429,
    "peso" : "0.160 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 19,
    "producto" : "pelacable",
    "img": "./imagenes/pelacable.jpg",
    "precio" : 2373,
    "peso" : "0.200 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
]