const herramientas = [ {
    "id" : 1,
    "producto" : "cutter profecinal",
    "precio" : 798,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},   
{
    "id" : 2,
    "producto" : "pinza pico de loro",
    "precio" : 1768,
    "peso" : "0.180 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},  
{
    "id" : 3,
    "producto" : "llaves combinadas",
    "precio" : 4298,
    "peso" : "0.220 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 4,
    "producto" : "pinza sacabocados multiple",
    "precio" : 1498,
    "peso" : "0.150 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 5,
    "producto" : "torquimetro de zafe",
    "precio" : 12398,
    "peso" : "1.930 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},

{
    "id" : 6,
    "producto" : "caja de herramientas",
    "precio" : 10798,
    "peso" : "3.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 7,
    "producto" : "banco de trabajo regulable",
    "precio" : 8798,
    "peso" : "5.500 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 8,
    "producto" : "set de prensas x 3",
    "precio" : 1498,
    "peso" : "0.890 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 9,
    "producto" : "nivel de aluminio reforzado",
    "precio" : 1050,
    "peso" : "0.110 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 10,
    "producto" : "engrampadora profecional",
    "precio" : 2380,
    "peso" : "0.450 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 11,
    "producto" : "serrucho profecional 3 filos",
    "precio" : 1798,
    "peso" : "0.320 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 12,
    "producto" : "gavetero plastico",
    "precio" : 730,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 13,
    "producto" : "escuadra combinada",
    "precio" : 1495,
    "peso" : "0.130 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 14,
    "producto" : "destornillador de impacto",
    "precio" : 6798,
    "peso" : "1.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 15,
    "producto" : "pescatornillo flexible",
    "precio" : 1260,
    "peso" : "0.090 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 16,
    "producto" : "juego de tarrajas y machos",
    "precio" : 40798,
    "peso" : "0.100 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
{
    "id" : 17,
    "producto" : "lapices de carpintero",
    "precio" : 858,
    "peso" : "0.080 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 18,
    "producto" : "cepillo de bronce",
    "precio" : 429,
    "peso" : "0.160 kg",
    "categoria" : "herramintas de mano",
    "oferta" : false,
},
{
    "id" : 19,
    "producto" : "tijera corta chapa(corte recto)",
    "precio" : 1373,
    "peso" : "0.200 kg",
    "categoria" : "herramintas de mano",
    "oferta" : true,
},
]